name: pipeline

on: 
  [push, pull_request]

jobs: 
  test:
    runs-on: ubuntu-latest  # Corrigido de ubuntu-lasted para ubuntu-latest
    
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      ALGORITHM: ${{ secrets.ALGORITHM }}
      ACCESS_TOKEN_EXPIRE_MINUTES: ${{ secrets.ACCESS_TOKEN_EXPIRE_MINUTES }}
    
    steps: 
      - name: Copy Files from Repo
        uses: actions/checkout@v3

      - name: Install Python
        uses: actions/setup-python@v5  # Corrigido para a versão v5
        with:
          python-version: '3.13'

      - name: Install Poetry
        run: pipx install poetry

      - name: Install Dependenc
        run: poetry install     

      - name: Execute tests
        run: poetry run task test    
